### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by solariz** [shirayu/withings-dumper#1]
Hi,

thanks for the script. Using it to pull the API and push to my local influx db.

Strange thing is, on my account it is working like a charm. If I try to read the account form my wife I can generate the token and confirm but as soon as I try to fetch data I receive a exception:

```
python3 dump.py -c config.lu.json
Traceback (most recent call last):
  File "dump.py", line 99, in <module>
    main()
  File "dump.py", line 85, in main
    outs = get_data(cfg, opts.startdate, opts.enddate)
  File "dump.py", line 50, in get_data
    measures = client.get_measures()
  File "/usr/local/lib/python3.4/dist-packages/withings/__init__.py", line 138, in get_measures
    r = self.request('measure', 'getmeas', kwargs)
  File "/usr/local/lib/python3.4/dist-packages/withings/__init__.py", line 116, in request
    raise Exception("Error code %s" % response['status'])
Exception: Error code 283
```

Any Idea where I can dig?

**Comment by solariz** [comment]
Just as a note to whom ever run in the same Issue.
My Wife had a pretty old Account, former created as Withing "Partner Share" Account. Looks like this was the reason. I exported all the data from the nokia health Dashbaord, created a new account for her, import again and with the new account it's working.
